### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by khoroo** [tillahoffmann/wastewater-catchment-areas#9]
```
data/geoportal.statistics.gov.uk/countries20_BGC.zip: FAILED 
data/geoportal.statistics.gov.uk/LSOA11_BGC.zip: FAILED
```

Checksums fail as links for geoportal data have rotted - see [`countries20_BGC.zip`](https://opendata.arcgis.com/api/v3/datasets/ad26732b081049d797620753db953185_0/downloads/data?format=shp&spatialRefId=27700)

**Comment by tillahoffmann** [comment]
I've updated all links with permalinks. See #10 for details. Let me know if you have follow-up questions or problems with downloading the data from the web archive. Thanks for reporting.
